### ISSUE TITLE
Scan error

### ISSUE THREAD

**Issue by xbassols** [IanHarvey/bluepy#121]
Hi Ian,

I've been dealing with this issue and I can't figure out a way to solve it.

```
Scanning for devices...
Running  /root/bluepy/bluepy/bluepy-helper
Sent:  le on

Got: 'rsp=$mgmt code=$protoerr\n'
Stopping  /root/bluepy/bluepy/bluepy-helper
Traceback (most recent call last):
  File "./blescan.py", line 133, in <module>
    main()
  File "./blescan.py", line 115, in main
    devices = scanner.scan(arg.timeout)
  File "/root/bluepy/bluepy/btle.py", line 631, in scan
    self.start()
  File "/root/bluepy/bluepy/btle.py", line 569, in start
    self._mgmtCmd("le on")
  File "/root/bluepy/bluepy/btle.py", line 240, in _mgmtCmd
    "Failed to execute mgmt cmd '%s'" % (cmd))
btle.BTLEException: Failed to execute mgmt cmd 'le on'
```

I had to modify from . import btle to import btle inside the file blescan.py in order to import the library but then the issue above happens.

I'm testing with python3.4 and the file is being executed as python3 blescan.py -v (I also tried with just python blescan.py -v).

I looked at the issue #94 so I'm running the code as root and Debugging is set to True.

I've tried multiple things but can't make it work.

Any insights?

Thanks!

**Comment by bbreton09** [comment]
Hello, have you found a solution? I find the same error on an Orange PI Zero under Armbian.
Error: "btle.BTLEException: Failed to execute mgmt cmd 'on'"
A scan with hcitool lescan works perfectly.

Thank you

**Comment by lionlife** [comment]
Same issue with Orange Pi PC Plus under Armbian.
Same code works on Rapsberry Pi 3.

**Comment by bbreton09** [comment]
For Armbian just use kernel developper in version 4.x solve issue on Orange PI Zero

**Comment by edouardkleinhans** [comment]
any news on Orange Pi PC plus under Armbian ?

**Comment by robertcsakany** [comment]
+1
