### ISSUE TITLE
btle.py python3 problem when there's nothing to scan

### ISSUE THREAD

**Issue by casab** [IanHarvey/bluepy#145]
When I try to scan for surrounding ble beacons and collect advertising data it works just fine. But when I remove or power off every ble beacon near me I get this error with python3, ps: it works fine with python2;

`Traceback (most recent call last):
  File "beacon.py", line 29, in <module>
    devices = scanner.scan(2)
  File "/usr/local/lib/python3.4/dist-packages/bluepy/btle.py", line 633, in scan
    self.stop()
  File "/usr/local/lib/python3.4/dist-packages/bluepy/btle.py", line 582, in stop
    self._mgmtCmd("scanend")
  File "/usr/local/lib/python3.4/dist-packages/bluepy/btle.py", line 236, in _mgmtCmd
    rsp = self._waitResp('mgmt')
  File "/usr/local/lib/python3.4/dist-packages/bluepy/btle.py", line 301, in _waitResp
    raise BTLEException(BTLEException.INTERNAL_ERROR, "Unexpected response (%s)" % respType)
bluepy.btle.BTLEException: Unexpected response (stat)`

And here's my code;
`from bluepy.btle import Scanner, DefaultDelegate

class ScanDelegate(DefaultDelegate):

        def __init__(self):
                DefaultDelegate.__init__(self)

        def handleDiscovery(self,dev,isNewDev, isNewData):
                if isNewData:
                        try:
                                address = dev.addr
                                rssi = dev.rssi
                                ibeacon_data = dev.getScanData()[3][2][8:50]
                                uuid = ibeacon_data[0:32]
                                major_id = int(ibeacon_data[32:36], 16)
                                minor_id = int(ibeacon_data[36:40], 16)
                                service_data = dev.getScanData()[2][2][6:14]
                                x,y,z,temp = [self.hex_to_int_16(service_data[i:i+2]) for i in range(0,len(service_data),2)]
                                print("address: %s uuid: %s major: %d minor: %d rssi: %d x: %d y: %d z: %d temp: %d" % (address,uuid,major_id,minor_id,rssi,x,y,z,temp))
                        except IndexError: pass

        def hex_to_int_16(self, x):
                intval = int(x, 16)
                if intval>= 128: intval -= 256
                return intval
scanner = Scanner().withDelegate(ScanDelegate())
for i in range(100):
        devices = scanner.scan(2)`

**Comment by caiki** [comment]
Hi, have you solved this problem? I have a similar problem with bluepy.btle in python 3.5, in python 2 works well.
