### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by soulraven** [IanHarvey/bluepy#160]
Hello, i have try to connect using your lib to a CC2650 SensorTag but i get this error:
`Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/opt/pyProjectsEnv/weatherStation/local/lib/python2.7/site-packages/bluepy/sensortag.py", line 331, in __init__
    Peripheral.__init__(self,addr)
  File "/opt/pyProjectsEnv/weatherStation/local/lib/python2.7/site-packages/bluepy/btle.py", line 318, in __init__
    self.connect(deviceAddr, addrType, iface)
  File "/opt/pyProjectsEnv/weatherStation/local/lib/python2.7/site-packages/bluepy/btle.py", line 353, in connect
    self._startHelper()
  File "/opt/pyProjectsEnv/weatherStation/local/lib/python2.7/site-packages/bluepy/btle.py", line 210, in _startHelper
    universal_newlines=True)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
`

any ideea i am using BT adaptor ASUS USB-BT400

any idea about this error?

**Comment by rytilahti** [comment]
Install from git if possible (pip install git+https://github.com/IanHarvey/bluepy.git), or compile bluepy-helper manually, maybe that fixes it?

**Comment by blendmaster** [comment]
I had the same issue with the the regular `pip install bluepy` version (on ubuntu 16.04 / python 2.7 from official repos). I wonder why installing it from git fixes this issue.

**Comment by abusquets** [comment]
I have the same problem, also with ubuntu 16.04 and python 2.7

**Comment by IanHarvey** [comment]
This has the same symptoms as #158. If I could trouble you to post any further information you have to that issue, it would help.

Thanks
Ian
