### ISSUE TITLE
Fail to scan, mgmtCmd and ParseRep Issue

### ISSUE THREAD

**Issue by stretchsenselouisgermain** [IanHarvey/bluepy#179]
Hey Ian,

I recently have an issue using your API.
In a first time it worked well when I add a bit of code to your blescan.py to receive my bluetoothLE sensors data.
My idea after was to create in the btle.py all my class and functions and call which ones I want in a separate main.

So I transfered every piece of the blescan.py in the btle.py to use it as a library and it worked well, all the links are created but when I'm willing to use your 

devices = scanner.scan(arg.timeout)

It sends me this error : 

Running: /home/pi/Desktop/Unknown/main.py (Thu Mar 30 02:25:11 2017)

Running  /home/pi/Desktop/Unknown/bluepy-helper
Sent:  le on

Got: ''

Traceback (most recent call last):
  File "/home/pi/Desktop/Unknown/main.py", line 15, in <module>
    main()
  File "/home/pi/Desktop/Unknown/main.py", line 10, in main
    UnknownObject.startScanning()
  File "/home/pi/Desktop/Unknown/UnknownLibrary.py", line 927, in startScanning
    devicesAvailable = scanner.scan(10)
  File "/home/pi/Desktop/Unknown/UnknownLibrary.py", line 732, in scan
    self.start()
  File "/home/pi/Desktop/Unknown/UnknownLibrary.py", line 665, in start
    self._mgmtCmd("le on")
  File "/home/pi/Desktop/Unknown/UnknownLibrary.py", line 298, in _mgmtCmd
    rsp = self._waitResp('mgmt')
  File "/home/pi/Desktop/Unknown/UnknownLibrary.py", line 348, in _waitResp
    resp = BluepyHelper.parseResp(rv)
  File "/home/pi/Desktop/Unknown/UnknownLibrary.py", line 311, in parseResp
    (tag, tval) = item.split('=')
ValueError: need more than 1 value to unpack

It is pretty disturbing because I'm only doing the same as you in different files.
I thought it was about running the program as root, but it does the same error.

If someone has any ideas, I'm lost on this I feel I'd done everything.

If you need more specification, tell me.

Big thanks.

Louis

**Comment by stretchsenselouisgermain** [comment]
The error was mine after I changed a parameter in the BluepyHelper class.

Then I close this issue.

Louis
