### ISSUE TITLE
Getting characteristics for empty services throws exception

### ISSUE THREAD

**Issue by chrisp110** [IanHarvey/bluepy#181]
bluepy seems to be unable to cope with peripherals which have empty services (i.e. they have no characteristics).

If you get services characteristics by calling the 'getCharacteristics()' method on an instance of a 'Service' object and that service has no characteristics, the exception "bluepy.btle.BTLEException: Error from Bluetooth stack (comerr)" is thrown.

"What is the point of services with no characteristics?", you may well ask but it seems that the BLE specification mandates the Generic Attribute service (0x1801) which includes only a single characteristic which is *optional*. So, it would seem that peripherals that have empty services might actually be quite common. Indeed I experienced this issue while trying to connect to Google's Daydream VR controller.

**Comment by chrisp110** [comment]
Here is the stack trace that gets dumped when this issue occurs:

> Traceback (most recent call last):
  File "bluepy_test.py", line 32, in <module>
    characteristics = service.getCharacteristics()
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 108, in getCharacteristics
    self.chars = self.peripheral.getCharacteristics(self.hndStart, self.hndEnd)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 468, in getCharacteristics
    rsp = self._getResp('find')
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 370, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 333, in _waitResp
    raise BTLEException(BTLEException.COMM_ERROR, "Error from Bluetooth stack (%s)" % errcode)
bluepy.btle.BTLEException: Error from Bluetooth stack (comerr)

Diving into the relevant code a bit deeper it seems the issue relates to the handle range that gets passed on to the lower layers. In the case when a service has no characteristics, the start and end handle values are the same which is interpreted as an invalid range by the lower layers.

This can be easily fixed by checking the handle range before passing it on to the lower layers. If the start and end handles are the same then the service cannot contain any characteristics and `Service.getCharacteristics()` should simply return an empty list (or maybe `None`?).

**Comment by chrisp110** [comment]
Thanks for merging. Confirmed as fixed. Closing issue.
