### ISSUE TITLE
BTLEException: Service Battery Service not found

### ISSUE THREAD

**Issue by pedrococa** [IanHarvey/bluepy#195]
I'm getting the following error with sensortag after updating bluepy:

```
Traceback (most recent call last):
  File "/usr/local/bin/sensortag", line 9, in <module>
    load_entry_point('bluepy==1.1.0', 'console_scripts', 'sensortag')()
  File "/usr/local/lib/python2.7/dist-packages/bluepy/sensortag.py", line 458, in main
    tag.battery.enable()
  File "/usr/local/lib/python2.7/dist-packages/bluepy/sensortag.py", line 26, in enable
    self.service = self.periph.getServiceByUUID(self.svcUUID)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 449, in getServiceByUUID
    raise BTLEException(BTLEException.GATT_ERROR, "Service %s not found" % (uuid.getCommonName()))
bluepy.btle.BTLEException: Service Battery Service not found
```

I was not able to resolve the issue with a reboot like is suggested on a similar issue ( #182 )

I'm using the sensortag on a NUC with Ubuntu 16.04

Any clue about what could be the issue?

**Comment by IanHarvey** [comment]
The Battery Service appears to be new in version 1.30 of the firmware. Are you able to update the firmware with TI's iOS/Android app to see if this fixes the problem?

Thanks
Ian
