### ISSUE TITLE
read microbit Characteristic: Insufficient Authentication

### ISSUE THREAD

**Issue by alcir** [IanHarvey/bluepy#234]
The Micro:bit is exposing the temperature service.
Using `bluetoothctl` I'm able to pair, connect to the device and to read the value of the Characteristic:

<pre>
[bluetooth]# connect E4:6D:B6:FC:83:A8 
Attempting to connect to E4:6D:B6:FC:83:A8
[CHG] Device E4:6D:B6:FC:83:A8 Connected: yes
Connection successful
[CHG] Device E4:6D:B6:FC:83:A8 ServicesResolved: yes
[BBC micro:bit]# select-attribute e95d9250-251d-470a-a062-fa1922dfa9a8
[BBC micro:bit:/service0021/char0022]# read
Attempting to read /org/bluez/hci0/dev_E4_6D_B6_FC_83_A8/service0021/char0022
[CHG] Attribute /org/bluez/hci0/dev_E4_6D_B6_FC_83_A8/service0021/char0022 Value:
  19                                               .               
  19                                               . 
</pre>

Using bluepy I get:

<pre>
Traceback (most recent call last):
  File "10blu.py", line 21, in <module>
    print(ch.read())
  File "/home/alessio/.local/lib/python2.7/site-packages/bluepy/btle.py", line 160, in read
    return self.peripheral.readCharacteristic(self.valHandle)
  File "/home/alessio/.local/lib/python2.7/site-packages/bluepy/btle.py", line 489, in readCharacteristic
    resp = self._getResp('rd')
  File "/home/alessio/.local/lib/python2.7/site-packages/bluepy/btle.py", line 369, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/home/alessio/.local/lib/python2.7/site-packages/bluepy/btle.py", line 332, in _waitResp
    raise BTLEException(BTLEException.COMM_ERROR, "Error from Bluetooth stack (%s)" % errcode)
bluepy.btle.BTLEException: Error from Bluetooth stack (comerr)
</pre>

This is the program:

<pre>
from bluepy import btle

p = btle.Peripheral("XX:XX:XX:XX:XX:XX", btle.ADDR_TYPE_RANDOM)

svc = p.getServiceByUUID("e95d6100-251d-470a-a062-fa1922dfa9a8")
ch = svc.getCharacteristics("e95d9250-251d-470a-a062-fa1922dfa9a8")[0]

print(ch.read())
</pre>

Using Wireshark to sniff the traffic, it seems that, only using bluepy, I get something like `Error Code: Insufficient Authentication (0x05)`

**Comment by alcir** [comment]
Adding `p.setSecurityLevel("medium")` solved the issue
