### ISSUE TITLE
IanHarvey/bluepy 

### ISSUE THREAD

**Issue by PRABHULINGAYYA** [IanHarvey/bluepy#247]
pi@raspberrypi:~/Desktop/bluepy1/bluepy $ python originalsenortag.py --all B0:B4:48:BA:05:01
Connecting to B0:B4:48:BA:05:01
Traceback (most recent call last):
  File "originalsenortag.py", line 498, in <module>
    main()
  File "originalsenortag.py", line 460, in main
    tag.keypress.enable()
  File "originalsenortag.py", line 310, in enable
    SensorBase.enable(self)
  File "originalsenortag.py", line 28, in enable
    self.ctrl = self.service.getCharacteristics(self.ctrlUUID) [0]
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 107, in getCharacteristics
    self.chars = [] if self.hndEnd <= self.hndStart else self.peripheral.getCharacteristics(self.hndStart, self.hndEnd)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 467, in getCharacteristics
    rsp = self._getResp('find')
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 369, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python2.7/dist-packages/bluepy/btle.py", line 326, in _waitResp
    raise BTLEException(BTLEException.DISCONNECTED, "Device disconnected")
bluepy.btle.BTLEException: Device disconnected

**Comment by mdxs** [comment]
@PRABHULINGAYYA Guess this can be closed by now?  Most likely something else was connected with the device and thus it wasn't available for being connected to from the machine running the command; so that it timed out. As you indicated that it worked before, this isn't an issue with `bluepy` but rather a result of a particular situation.
