### ISSUE TITLE
Unable to scan Bluetooth device in bleah

### ISSUE THREAD

**Issue by Vaibhav330900** [IanHarvey/bluepy#279]
Hey, While running **Sudo bleah -t0**, I am getting this error.

Traceback (most recent call last):
  File "/usr/local/bin/bleah", line 4, in <module>
    __import__('pkg_resources').run_script('bleah==1.0.0', 'bleah')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/bleah-1.0.0-py2.7.egg/EGG-INFO/scripts/bleah", line 148, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/bleah-1.0.0-py2.7.egg/EGG-INFO/scripts/bleah", line 108, in main
    devices = start_scan(args)
  File "/usr/local/lib/python2.7/dist-packages/bleah-1.0.0-py2.7.egg/bleah/scan.py", line 163, in start_scan
    return scanner.scan(args.timeout)
  File "/usr/local/lib/python2.7/dist-packages/bluepy-1.1.4-py2.7.egg/bluepy/btle.py", line 735, in scan
    self.process(timeout)
  File "/usr/local/lib/python2.7/dist-packages/bleah-1.0.0-py2.7.egg/bleah/scan.py", line 78, in process
    self.delegate.handleDiscovery(dev, (dev.updateCount <= 1), isNewData)
  File "/usr/local/lib/python2.7/dist-packages/bleah-1.0.0-py2.7.egg/bleah/scan.py", line 135, in handleDiscovery
    for ( tag, desc, val ) in dev.getScanData():
  File "/usr/local/lib/python2.7/dist-packages/bluepy-1.1.4-py2.7.egg/bluepy/btle.py", line 656, in getScanData
    for sdid in self.scanData.keys() ]
  File "/usr/local/lib/python2.7/dist-packages/bluepy-1.1.4-py2.7.egg/bluepy/btle.py", line 651, in getValueText
    return str(self.getValue(sdid))
  File "/usr/local/lib/python2.7/dist-packages/bluepy-1.1.4-py2.7.egg/bluepy/btle.py", line 642, in getValue
    return self._decodeUUID(val,2)
  File "/usr/local/lib/python2.7/dist-packages/bluepy-1.1.4-py2.7.egg/bluepy/btle.py", line 622, in _decodeUUID
    rs = ("%02X" % val[i]) + rs
TypeError: %X format: a number is required, not str

**Comment by parkerlreed** [comment]
Same here. Could this possibly be an issue on the bleah side?
