### ISSUE TITLE
sensortag.py fails to connect: "No such file or directory"

### ISSUE THREAD

**Issue by hoonkai** [IanHarvey/bluepy#91]
Hi

I haven't got a TI SensorTag but I do have a PCB with the CC2541 on it. I'm trying to see how `sensortag.py` plays with my PCB, so I try connecting to it using `python sensortag.py --all <MAC>`. Immediately I get an error saying

    Traceback (most recent call last):
      File "bluepy/sensortag.py", line 293, in <module>
        main()
      File "bluepy/sensortag.py", line 247, in main
        tag = SensorTag(arg.host)
      File "bluepy/sensortag.py", line 179, in __init__
        Peripheral.__init__(self,addr)
      File "/Users/mman/Projects/Bluetooth/test_bluetooth/bluepy/bluepy/btle.py", line 323, in __init__
        self.connect(addr, self.addrType, self.iface)
      File "/Users/mman/Projects/Bluetooth/test_bluetooth/bluepy/bluepy/btle.py", line 358, in connect
        self._startHelper()
      File "/Users/mman/Projects/Bluetooth/test_bluetooth/bluepy/bluepy/btle.py", line 210, in _startHelper
        universal_newlines=True)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 709, in __init__
        errread, errwrite)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1326, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory```

This happens isn't because my board isn't a Sensor Tag - right? Am I missing something?

Could `bluepy` be run on OS X? Is `bluez` built specifically for Linux since OS X already has its own Bluetooth stack?

Thanks

**Comment by jhgorse** [comment]
I see the same issue, but on linux. What was the outcome?
