### ISSUE TITLE
Permissions problem

### ISSUE THREAD

**Issue by mph070770** [IanHarvey/bluepy#98]
Hello. I have the following simple test:

```
from btle import Scanner

sc = Scanner()
sc.scan(timeout=5)
```

and I get the following error:

```
pydev debugger: starting (pid: 14866)
Traceback (most recent call last):
  File "/home/parallels/Projects/liclipse/plugins/org.python.pydev_4.2.0.201507051114/pysrc/pydevd.py", line 2283, in <module>
    globals = debugger.run(setup['file'], None, None)
  File "/home/parallels/Projects/liclipse/plugins/org.python.pydev_4.2.0.201507051114/pysrc/pydevd.py", line 1709, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/parallels/Documents/LiClipse Workspace/btle/main.py", line 4, in <module>
    sc.scan(timeout=5)
  File "/usr/local/lib/python2.7/dist-packages/btle.py", line 631, in scan
    self.start()
  File "/usr/local/lib/python2.7/dist-packages/btle.py", line 569, in start
    self._mgmtCmd("le on")
  File "/usr/local/lib/python2.7/dist-packages/btle.py", line 236, in _mgmtCmd
    rsp = self._waitResp('mgmt')
  File "/usr/local/lib/python2.7/dist-packages/btle.py", line 294, in _waitResp
    raise BTLEException(BTLEException.MGMT_ERROR, "Management not available (permissions problem?)")
btle.BTLEException: Management not available (permissions problem?)
```

what am I doing wrong??

**Comment by mph070770** [comment]
I've moved the bluepy files into my liclipse workspace and it's working. Not ideal but ok to get me going until I have time to debug why.

**Comment by stretchsenselouisgermain** [comment]
Hey,

I know this subject is close, but I have exactly the same problem as you, the only difference is that I already put the bluepy files into my workspace and  it still doesn't work, can you give me a hand with this on how do you moved the files and make your code work?

**Comment by abaz21** [comment]
I'm having this same error. Please let me know if you are able to describe the solution.

**Comment by brian-lesschwab** [comment]
@abaz21 @mph070770, have either of you solved this problem? trying to get it to work on a raspberry pi
